### PR TITLE
Load ticker messages from config

### LINKED ISSUE #6: Load ticker messages from config file
Currently, ticker messages are written directly in the source codes. It'd be better to put them in its config file and load them.

### PR DESCRIPTION
**Pull request by DigiEggz**
Loads the ticker messages from the main config.toml file. Closes #6.

### CODE REVIEW

**Comment by DigiEggz** [comment]
This is my first time writing Rust code, so please excuse any sloppiness. Open to changes or suggestions!

**Comment by jidoc01** [comment]
Thank you for your contribution to our project! I will check it soon.

**Comment by jidoc01** [comment]
Sorry for my late reply here. Other than the one above, I am okay with the current modification.

**Comment by DigiEggz** [comment]
> Sorry for my late reply here. Other than the one above, I am okay with the current modification.

Is there anything you'd like me to change before you merge? Sorry if I missed something.

**Comment by jidoc01** [comment]
> > Sorry for my late reply here. Other than the one above, I am okay with the current modification.
> 
> Is there anything you'd like me to change before you merge? Sorry if I missed something.

Could you please remove the double colon preceding an external module name `config`? You can check my review above.

**Comment by DigiEggz** [comment]
> > > Sorry for my late reply here. Other than the one above, I am okay with the current modification.
> > 
> > 
> > Is there anything you'd like me to change before you merge? Sorry if I missed something.
> 
> Could you please remove the double colon preceding an external module name `config`? You can check my review above.

I can't see the review for some reason, but I will make suggested change. It may be for the reason talked about here: https://github.com/orgs/community/discussions/30638

**Comment by jidoc01** [comment]
> > > > Sorry for my late reply here. Other than the one above, I am okay with the current modification.
> > > 
> > > 
> > > Is there anything you'd like me to change before you merge? Sorry if I missed something.
> > 
> > 
> > Could you please remove the double colon preceding an external module name `config`? You can check my review above.
> 
> I can't see the review for some reason, but I will make suggested change. The review section is blank as well. It may be for the reason talked about here: https://github.com/orgs/community/discussions/30638
> 
> **Edit**: When I remove the double colon, I get the following error:
> 
> ```
> `config` is ambiguous
> note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
> help: use `::config` to refer to this crate unambiguously
> ```

> The review section is blank as well.

Thank you for letting me know. Let me check it.

> I get the following error

Ooh, your current mod declares `config` as a public module since a login handler uses it now that is why the conflict occurs. You can let it be. All good!

**Pull request merged**
